#!/bin/sh
ssh devops@192.168.29.81 <<EOF
 git clone https://github.com/trajeshk/node-app.git
 apt-get update --fix-missing 
 sudo  apt install -y npm
 npm install — production
 pm2 restart all
 exit
EOF
